name: quickhire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1

  # Routing
  go_router: ^15.1.2

  # Splash Screen
  flutter_native_splash: ^2.4.6

  # State Management
  flutter_riverpod: ^2.6.1

  # Firebase Related
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0

  # Image Picking
  image_picker: ^1.1.2
  
  # Networking
  connectivity_plus: ^6.1.4
  http: ^1.4.0

  # Maps and Location
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  
  # Other Dependencies
  skeletonizer: ^2.1.0+1
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app_logo_zoomed.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  image_path: "assets/images/app_logo_512.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800
